name: Release npm
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
          run_install: true
      - name: Configure committer
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Build
        run: |
          pnpm install
          pnpm build
      - name: publish
        run: |
          pnpm publish -r --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Read version
        id: version
        uses: ashley-taylor/read-json-property-action@v1.0
        with:
          path: ./packages/vue-star-plus/package.json
          property: version
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{steps.version.outputs.value}}
          body: body_v${{steps.version.outputs.value}}
          draft: false
          prerelease: false
